Document: easyzone
Title: Debian easyzone Manual
Author: <insert document author here>
Abstract: This manual describes what easyzone is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/easyzone/easyzone.sgml.gz

Format: postscript
Files: /usr/share/doc/easyzone/easyzone.ps.gz

Format: text
Files: /usr/share/doc/easyzone/easyzone.text.gz

Format: HTML
Index: /usr/share/doc/easyzone/html/index.html
Files: /usr/share/doc/easyzone/html/*.html
